name: Update Epic Subtask
on:
  issues:
    types: [edited, labeled]
jobs:
  handle-epics:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ACTION_TOKEN exists
        run: |
          if [ -z "${{ secrets.ACTION_TOKEN }}" ]; then
            echo "ACTION_TOKEN does not exist"
            exit 1
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check is has Epic label
        id: check-epic-label
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.ACTION_TOKEN}}
          script: |
            const label = context.payload.issue.labels.find(label => label.name === 'Epic')
            if (label) {
              return true
            }
            return false

      - name: Install dependencies
        if: steps.check-epic-label.outputs.result == 'true'
        run: |
          npm install @actions/github
          npm install @actions/core

      - name: Get issue number
        if: steps.check-epic-label.outputs.result == 'true'
        id: get-epic-issue-number
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.ACTION_TOKEN}}
          script: |
            const issueNumber = context.payload.issue.number
            return issueNumber

      - name: Log issue number
        if: steps.check-epic-label.outputs.result == 'true'
        run: |
          echo "The Epic Issue number is: ${{steps.get-epic-issue-number.outputs.result}}"


      - name: Get issues mentioned in body
        if: steps.check-epic-label.outputs.result == 'true'
        id: get-subtasks
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.ACTION_TOKEN}}
          script: |
              const body = context.payload.issue.body
              const regex = /- \[ \] #(\d+)/g
              const issues = body.match(regex)
              const rawIssueIds = issues.map(match => parseInt(match.split("#")[1]));
              return rawIssueIds.toString()

      - name: Log issues
        if: steps.check-epic-label.outputs.result == 'true'
        run: |
          echo "The sub taks are: ${{steps.get-subtasks.outputs.result}}"
      - name: Update Epic Subtask
        if: steps.check-epic-label.outputs.result == 'true'
        id: update-subtasks
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.ACTION_TOKEN}}
          script: |
            const githubLib = require('@actions/github');
            const githubCore = require('@actions/core');

            const githubContext = githubLib.context;
            const token = process.env.GITHUB_TOKEN;
            const octokit = githubLib.getOctokit({ auth: token })
            const epicIssueNumber = core.getInput('get-epic-issue-number-result');
            const subTaskIssueNumbers = core.getInput('get-subtasks-result');
            console.log({subTaskIssueNumbers})
            log({ prevStep: process.env['get-epic-issue-number'], epicIssueNumber} )
            const promises = subTaskIssueNumbers.map( subTaskIssueNumber => {
              return octokit.rest.issues.update({
                owner: githubContext.repo.owner,
                repo: githubContext.repo.repo,
                issue_number: subTaskIssueNumber,
                custom_field_name: "From Epic",
                custom_field_value: epicIssueNumber
                });
              });
            await Promise.all(promises);
        env:
          GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}
