# i have a mono repo with Nx that contains 3 applications,
#  one called "my-growth" which is the frontend, other one is "my-growth-e2e"
# and the other one is "api". The "api" application is built with NestJs.
# I want to generate a Github Action to run the Cypress test over "my-growth-e2e"
# but it should run first the "api" app which contains the api logic. The "api" is served using npm run serve:api
# and the cypress test is served using npm nx e2e my-growth-e2e
name: CI

on:
  pull_request:
  push:
    branches:
      - develop
env:
  TERM: xterm-256color
  CYPRESS_download_on_fail: true
  NODE_VERSION: 18

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - name: Log
      run: |
        echo "Starting... XD"
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: cypress-io/github-action@v4
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-

    - name: Install nrwl CLI dependencies
      run: npm install -g @nrwl/cli

    - name: Install Nx dependencies
      run: npm install nx

    - name: Install dependencies
      run: npm ci

    - name: Run Cypress
      run: npx nx serve my-growth-e2e:e2e
      env:
        TERM: ${{ env.TERM }}
        CYPRESS_download_on_fail: ${{ env.CYPRESS_download_on_fail }}

    - name: Download cypress videos
      if: failure()
      uses: actions/download-artifact@v3
      with:
        name: cypress-videos
        path: cypress/downloads
