# i have a mono repo with Nx that contains 3 applications,
#  one called "my-growth" which is the frontend, other one is "my-growth-e2e"
# and the other one is "api". The "api" application is built with NestJs.
# I want to generate a Github Action to run the Cypress test over "my-growth-e2e"
# but it should run first the "api" app which contains the api logic. The "api" is served using npm run serve:api
# and the cypress test is served using npm nx e2e my-growth-e2e
name: CI

on:
  pull_request:
  push:
    branches:
      - develop

env:
  NODE_ENV: development

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - name: Log
      run: |
        echo "Starting... XD"
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

  run-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run api
      run: npm run serve:api

    - name: Run Cypress
      run: npm nx e2e my-growth-e2e

    - name: Download the error videos
      uses: actions/download-artifact@v1
      with:
        name: cypress/videos
        path: cypress/videos
