name: Log Issue Body

on:
  issues:
    types: [edited]

jobs:
  log_body:
    runs-on: ubuntu-latest

    steps:
      - name: Get Issue Body
        id: get_body
        uses: actions/bin/filter@v1
        with:
          args: echo "${{ toJson(github.event.issue) }}" | jq '.body'
        env:
          ISSUE_BODY: ${{ steps.get_body.outputs.stdout }}

      - name: Log Issue Body
        id: log_body
        run: echo "$ISSUE_BODY"
