name: Log Issue Body

on:
  issues:
    types: [edited]

jobs:
  log_body:
    runs-on: ubuntu-latest

    steps:
      - name: Get Issue Body
        id: get_body
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.ACTION_TOKEN}}
          script: |
            const body = context.payload.issue.body
            return body
      - name: Log Issue Body
        run: |
          echo "The issue body is: ${{steps.get_body.outputs.result}}"
