name: Log Issue Body

on:
  issues:
    types: [edited]

jobs:
  log_body:
    runs-on: ubuntu-latest

    steps:
      - name: Get Issue Body
        id: get_body
        uses: actions/github-script@v5
        with:
          script: |
            const body = github.context.payload.issue.body;
            return body;

      - name: Log Body
        run: |
          echo "The body is: ${{steps.get_body.outputs.result}}"
